Add CMake export
Olympus-HPC/proteus pull request #31
Opened 2024-11-06 23:00 UTC by davidbeckingsale

A user can `find_package(proteus)` and then depend on the targets `proteus` and `ProteusPass` to automatically get the correct compile and link flags.

2024-11-06 23:00 UTC, davidbeckingsale commented on CMakeLists.txt
> +  lib/cmake/proteus)
```suggestion
  lib/cmake/proteus)
  
```

2024-11-06 23:01 UTC, davidbeckingsale commented on cmake/proteusConfig.cmake.in
> +check_required_components("@PROJECT_NAME@")
```suggestion
check_required_components("@PROJECT_NAME@")

```

2024-11-07 01:08 UTC, ggeorgakoudis requested changes
Looks good, thank you! Few minor comments.

2024-11-07 01:08 UTC, ggeorgakoudis commented on lib/CMakeLists.txt
> +install(
Add also header libraries for JitEngine* as the API to clients

2024-11-07 01:08 UTC, ggeorgakoudis commented on pass/CMakeLists.txt
> +add_library(ProteusPass SHARED ProteusJitPass.cpp)
nit: Do we also want to rename the source file to `ProteusPass.cpp`?

2024-11-07 17:51 UTC, merged